apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: container-security-operator
spec:
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      name: container-security-operator-alm-owned
